### ISSUE TITLE
Two backend directories

### ISSUE THREAD

**Issue by yangy113** [Danielwu9226/community-currency-reframery#52] opened 2021-03-08 07:38 UTC
Version:
https://github.com/Danielwu9226/community-currency-reframery/blob/master/README.md

I just followed `README.md` to test the project, as it says:
![image](https://user-images.githubusercontent.com/70185196/110289034-d2931f80-8023-11eb-9585-8cdace24219c.png)

When I wanted to `cd into the backend directory`, I found there two `backend`s in the directory:
![image](https://user-images.githubusercontent.com/70185196/110289285-2d2c7b80-8024-11eb-9463-da2bd5f99a29.png)
![image](https://user-images.githubusercontent.com/70185196/110289334-3b7a9780-8024-11eb-8728-e8ae28a732f5.png)

I think `README.md` should claim which `backend` to get into.

**Comment by alishahimtiaz** [comment] 2021-04-01 05:15
It says cd into backend directory. Closing as this is intended behavior.

**Closed by alishahimtiaz** 2021-04-01 05:15 UTC
