### ISSUE TITLE
/getUnvalidatedUsers Doesn't Work at All

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#14] opened 2021-02-25 01:15 UTC
Following from the previous issues with unhandled 404 errors, while this is similar, it's not the same. Trying to make a GET request to ``/getUnvalidatedUsers`` never returns a normal output, and I assume it should at some point.

![image](https://user-images.githubusercontent.com/17243618/109088162-e4e49380-76dc-11eb-94b1-546b01b0cf1b.png)

**Comment by KristieTom12** [comment] 2021-02-26 23:20
This isn't my code base but it looks like this is again a routing error. Try `http://localhost:8000/getUnvalidatedUsers` (without the end slash). worked for me. Looks like this issue can be closed as it's a duplicate of their routing issue

**Closed** 2021-03-07 21:10 UTC
