### ISSUE TITLE
/forgotpassword should not so easily change passwords

### ISSUE THREAD

**Issue by KristieTom12** [Danielwu9226/community-currency-reframery#29] opened 2021-02-26 23:06 UTC
Using code at version latest master [068df999](https://github.com/Danielwu9226/community-currency-reframery/commit/068df999536b9714153b4a9d9cba4cbf9a8320f5)

Steps to reproduce:
1. create user "test@gmail.com"
2. invoke forgotpassword endpoint
```
curl --location --request POST 'http://localhost:8000/forgotpassword/' \
--header 'Content-Type: text/plain' \
--data-raw '{"email": "test@gmail.com", "password":"1243"}'
```
Response:
![image](https://user-images.githubusercontent.com/34824500/109364551-07051f80-785d-11eb-90d8-d0cef4c940ff.png)

There are two points to this:
1. It shouldn't be so easy to change any email's password without confirming the identity of who you are trying to change the email for
2. The endpoint name /forgotpassword should probably be renamed then to /changepassword since that name seems to encapsulate the functionality better

**Comment by alishahimtiaz** [comment] 2021-04-01 05:09
There is another step before this function can be called, closing as intended behavior.

**Closed by alishahimtiaz** 2021-04-01 05:09 UTC
