### ISSUE TITLE
/createSubCategory Fails Even with Proper Inputs

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#17] opened 2021-02-25 02:08 UTC
**Severity**: High

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: Okay, this time I actually tried to run the command properly. It still didn't work.

![image](https://user-images.githubusercontent.com/17243618/109092220-27f63500-76e4-11eb-97b1-ad6e4df63fd7.png)

And the command line output:

![image](https://user-images.githubusercontent.com/17243618/109092282-3cd2c880-76e4-11eb-8cb4-178b62f3b786.png)
![image](https://user-images.githubusercontent.com/17243618/109092300-46f4c700-76e4-11eb-9720-4c92b448eed7.png)
![image](https://user-images.githubusercontent.com/17243618/109092342-5bd15a80-76e4-11eb-939e-39453bc24eb1.png)

**Steps to Recreate**:
1. Follow the setup instructions and run the server.
2. Navigate to postman.com.
3. Try sending a request as indicated in the screenshot above.

**Comment by alishahimtiaz** [comment] 2021-04-01 03:20
There's a value error in your log trace, could not reproduce. Closing this ticket.

**Closed by alishahimtiaz** 2021-04-01 03:20 UTC
