### ISSUE TITLE
/getOrder returns an item even if item ID does not exist

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#48] opened 2021-03-04 01:45 UTC
Version:
https://github.com/Danielwu9226/community-currency-reframery/blob/master/README.md

Repro:
1. Run server
2. Make /getOrder with 12121 as value for key "id"

Observation:
![Screenshot from 2021-03-03 20-43-45](https://user-images.githubusercontent.com/35702189/109897904-68642e80-7c61-11eb-9cb4-a1cadf4bcdd8.png)

Expected:
Should have error handling and return ID does not exist instead of status code 200

**Comment by alishahimtiaz** [comment] 2021-04-01 05:14
The return code is intentional that a successful operation was performed. Closing as this is intended behavior.

**Closed by alishahimtiaz** 2021-04-01 05:14 UTC
